### ISSUE TITLE
Try new colormaps 

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/WaterAgeNeutralHabitats#22]
- [x] Create news JPEGs based on these colormaps (prepare_data.py)
- [x] Integrate in Legends + webmap pipeline
- [x] Deploy on server @sbancal 

[formatted_colormap_L.txt](https://github.com/EPFL-ENAC/WaterAgeNeutralHabitats/files/8131422/formatted_colormap_L.txt)
[formatted_colormap_ET2.txt](https://github.com/EPFL-ENAC/WaterAgeNeutralHabitats/files/8131424/formatted_colormap_ET2.txt)
[formatted_colormap_S.txt](https://github.com/EPFL-ENAC/WaterAgeNeutralHabitats/files/8131425/formatted_colormap_S.txt)

- [x] Provide final colormaps (decision on Feb 28th : No Change maps)
- [x] Confirm colormaps with researchers.

**Comment by sbancal** [comment]
![Screenshot from 2022-02-24 15-42-49](https://user-images.githubusercontent.com/895546/155546809-d4241578-fbd2-4f30-af90-f8df5c3ecfba.png)
Le Colormap pour Evap ne peut pas marcher. La 2ème valeur est déjà trop haute pour le range des données.

**Comment by pbenettin** [comment]
Hello @sbancal and @charlottegiseleweil, I write here our comments on the colormaps:

- Evapotranspiration: the legend dis not show yesterday (bug?). But otherwise the colorscale is great.

- Surface Runoff: the colorscale is good. I see that the limits I had included in the dictionary `table_fluxes.csv` were not optimal, I have now updated them

- Water storage: looking at the whole layout, we think the colorscale should better be in shades of grey, to clarify that it does not correspond with any timeseries. We know that with shades of grey it will be more difficult to see differences among maps, but it's not a problem and we think that making a stronger link with the timeseries is more important

- Soil leakage: we prefer a colorscale in shades of blue. You can take the colorscale of the water storage, which was very good. I also see that the limits I had included in the dictionary `table_fluxes.csv` were not optimal, I have now updated them

- In the timeseries, we would like to have the leakage in blues and the surface runoff in reds (you can really just shift them). This way, they will recall the map colors

- [not really a colormap issue, but I wasn't sure where to write this] Can you reorder the controls of the map variables to make them consistent with the order of the timeseries? This means having Surface Runoff on top, then Evapotranspiration, then Soil leakage and finally the Water Storage
